apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-servlet-deployment
  labels:
    app: main-servlet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-servlet
  template:
    metadata:
      labels:
        app: main-servlet
    spec:
      containers:
        - name: main-servlet-container
          image: geethanjali025/ks8repo:tag
          ports:
            - containerPort: 8080

